### PR TITLE
Make _fields.py assertion much more helpful

### PR DESCRIPTION
**Pull request by pwais**
Tracebacks like these are unhelpful, especially in nerfstudio where there are literally *eleventeen brazilian* fields that could be broken:

```
ns-train         --help
Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/nerfstudio/scripts/train.py", line 263, in entrypoint
    tyro.cli(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_cli.py", line 374, in _cli_impl
    parser_spec = _parsers.ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 279, in handle_field
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 443, in from_field
    subparser = ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 304, in handle_field
    return ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 304, in handle_field
    return ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 296, in handle_field
    if _fields.is_nested_type(field.typ, field.default):
  File "/usr/local/lib/python3.10/dist-packages/tyro/_unsafe_cache.py", line 33, in wrapped_f
    out = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 188, in is_nested_type
    _try_field_list_from_callable(typ, default_instance),
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 298, in _try_field_list_from_callable
    return field_list_from_class(cls, default_instance)
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 537, in _field_list_from_attrs
    assert attr_field.type is not None
AssertionError
```

With this change, now you can figure out _wat teh brizzoke_ really much faster!

```
ns-train         --help
Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/opt/nerfstudio/scripts/train.py", line 263, in entrypoint
    tyro.cli(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_cli.py", line 187, in cli
    output = _cli_impl(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_cli.py", line 374, in _cli_impl
    parser_spec = _parsers.ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 279, in handle_field
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 443, in from_field
    subparser = ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 304, in handle_field
    return ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 304, in handle_field
    return ParserSpecification.from_callable_or_type(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 106, in from_callable_or_type
    field_out = handle_field(
  File "/usr/local/lib/python3.10/dist-packages/tyro/_parsers.py", line 296, in handle_field
    if _fields.is_nested_type(field.typ, field.default):
  File "/usr/local/lib/python3.10/dist-packages/tyro/_unsafe_cache.py", line 33, in wrapped_f
    out = f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 188, in is_nested_type
    _try_field_list_from_callable(typ, default_instance),
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 298, in _try_field_list_from_callable
    return field_list_from_class(cls, default_instance)
  File "/usr/local/lib/python3.10/dist-packages/tyro/_fields.py", line 537, in _field_list_from_attrs
    assert attr_field.type is not None, attr_field
AssertionError: Attribute(name='save_debug_assets', default=False, validator=None, repr=True, eq=True, eq_key=None, order=True, order_key=None, hash=None, init=True, metadata=mappingproxy({}), type=None, converter=None, kw_only=False, inherited=False, on_setattr=None, alias='save_debug_assets')
```

➡️ Always leave breadcrumbs / messages in `assert`s.  In python the user will almost never see the local var values unless they're using e.g. `loguru` / `better-exceptions` / `pytest`.  

IMO tyro is sufficiently complexicationated that all the asserts should have useful messages.  So why did I get this assert in the first place? I have no idea tyro is too complexicationated! EI_TOO_MUCH_MAGIC  🪄🪄

### CODE REVIEW

**Comment by pwais** [comment]
@brentyi

**Comment by brentyi** [comment]
Thanks for the PR! Just to check: how did you end up fixing this?

**Comment by pwais** [comment]
i found out `tryo` appears to not like `attrs` any more.  `tyro` worked for me for a long time with `attrs` but i switched to `dataclass` and magically the error goes away.  i even downgraded tyro but got this traceback so i have no idea why tyro broke when i upgraded nerfstudio 🤷 🤷 🤷 🤷  to be frank, while i appreciate the difficulty of what tyro does, i am not a fan of it being part of nerfstudio, which already had tons of API instability and crazy bugs on its own.

**Comment by brentyi** [comment]
If you have a runnable example for `attrs` failing that would be appreciated, the `attrs` tests still pass but maybe some edge case is being missed?

> to be frank, while i appreciate the difficulty of what tyro does, i am not a fan of it being part of nerfstudio, which already has tons of API instability and crazy bugs on its own. i mean like imagine if yangqing jia decided to include a home-rolled protobuff instead of regular protobuf in caffe.

Thanks for your feedback, I still like `tyro` a lot but do recognize there are limitations 😛
Particular room for improvement in error messages + API clarity in terms of what's actually supported vs not supported.

**Pull request merged**
