### PR TITLE
Feature: Markers: SelectionFromEnumValues

### LINKED ISSUE #166: Feature: Configuration option to use `Enum` values instead of names for choices.
A common convention for Python `Enum` classes is to use all-uppercase names for the members of the enum. (This is the style used in the [standard library documentation](https://docs.python.org/3/library/enum.html), for example.) However, all-uppercase names can be somewhat visually-jarring if the rest of the CLI is all-lowercase, as is typical for CLI subcommands and option names. Furthermore, with the introduction of [`StrEnum`](https://docs.python.org/3/library/enum.html#enum.StrEnum) in Python 3.11, the `enum.auto` values for each name are the all-lowercase transformation of the name.

To get around this problem, one could, of course, extract all of the enum values and use those as a literals list. But, that is dual maintenance if the enum is being used for more than just CLI options. Consider the use case of selecting output formats, for example. To use a selected output format (JSON (`json`), pretty text (`pretty`), TOML (`toml`), etc...), after CLI parsing, someone may want to `match..case` on the enum or even call a dispatcher method on the enum itself. Imo, an enum is more maintainable (and easier to validate) than a collection of literals in case like this.

To make Tyro friendlier to string enums, would you consider an enhancement to provide a configuration option which would populate choices by enum value rather than name?

--

(Tyro is great, btw. I just discovered it a couple days ago after messing around with Typer (no dataclasses support, no natural separation of parsing from execution) and SimpleParsing (no PEP 593 support). Thanks for making this. It is beautiful and works as advertised.)

### PR DESCRIPTION
**Pull request by emcd**
* Add configuration marker: SelectionFromEnumValues

* Refactor instantiator production logic for types with automatically-populated choices. Encapsulation to keep related variables tracked togther.

Resolves #166 .

@brentyi : All linter checks and tests are passing. Not sure if you want anything additional for documentation; looks like you have an automatic generator which I did not look closely at.

Also, manual proof that it works as described and intended:
```python
>>> import dataclasses, enum, typing_extensions, tyro
>>> class Formats( enum.StrEnum ):
...     JSON = enum.auto( )
...     PRETTY = enum.auto( )
...
>>> @dataclasses.dataclass
... class Args:
...     format: typing_extensions.Annotated[ Formats, tyro.conf.SelectFromEnumValues ] = Formats.PRETTY
...
>>> tyro.cli( Args, args = [ '--format', 'json' ] )
Args(format=<Formats.JSON: 'json'>)
>>> tyro.cli( Args, args = [ '--format', 'pretty' ] )
Args(format=<Formats.PRETTY: 'pretty'>)
>>> tyro.cli( Args, args = [ ] )
Args(format=<Formats.PRETTY: 'pretty'>)
>>> tyro.cli( Args, args = [ '--help' ] )
```
```
usage: [-h] [--format {json,pretty}]

╭─ options ───────────────────────────────────────────────╮
│ -h, --help              show this help message and exit │
│ --format {json,pretty}  (default: pretty)               │
╰─────────────────────────────────────────────────────────╯
```

### CODE REVIEW

**Comment by emcd** [comment]
Code coverage error appears to be a Codecov rate-limiting issue.

However, I just realized that I missed the `Literal` case that you mentioned in the issue. I need to cover that and make tests accordingly. So, please do not merge yet.

**Comment by emcd** [comment]
@brentyi : I just added the enum names case for literal lists that I forgot earlier. Should be good to go.

**Comment by brentyi** [comment]
Thanks @emcd for the PR!! Just wanted to note that reviewing/merging this is on my to-do list, unfortunately this week has been busier than most...

**Comment by emcd** [comment]
No worries, @brentyi . Life (Ph.D. theses, etc...) comes first. I've been using a fork of your repo with my patch, so I'm not blocked.

I am going to file another feature request soon, though, but no pressure in responding to it.

**Comment by brentyi** [comment]
Thanks for understanding @emcd! I just pushed some minor changes to your branch, could you confirm that they look reasonable?

- You had defined some classes for handling the different ways of generating choices. I refactored a bit to make it more succinct / self-contained. It might be less type-safe.
- I relaxed the constraint that values need to be strings + added a test.

**Comment by emcd** [comment]
The changes seem good to me, @brentyi . I actually introduced the classes to make things a bit more self-contained so that we weren't working with two or three different related variables, side by side, in multiple places. But, I have no objection to what you have done.

I just added a commit to fix the example to match the renamed marker.

**Comment by brentyi** [comment]
Thanks for the fix! And the help with this feature. For the classes your explanation makes sense, seems like just a matter of personal taste. October is feeling like a "limit abstractions" month for me 😛

**Review by brentyi — APPROVED** [review]

**Pull request merged**
